### ISSUE TITLE
잠금화면에 추가해줬으면 하는 기능 

### ISSUE THREAD

**Issue by Temaca333** [junhg0211/SloOS#11]
시스템 종료 기능
   *첫스템 종료 탭은 투명하게

![_ 1](https://user-images.githubusercontent.com/44523100/47605511-3e235600-da42-11e8-8f10-cb99a079881b.png)
![_ 2](https://user-images.githubusercontent.com/44523100/47605512-3f548300-da42-11e8-97df-8e4dd081686a.png)
![_ _](https://user-images.githubusercontent.com/44523100/47605524-804c9780-da42-11e8-831a-de857ad0287e.png)

**Comment by Neder0615** [comment]
오옹ㅇ옹

**Comment by Neder0615** [comment]
오오오오

**Comment by junhg0211** [comment]
화면 오른쪽 위에 마우스 커서 올려놓고 0.5초동안 클릭하고 있으면 꺼집니다! 이것도 설정에 추가할 것이다
