### ISSUE TITLE
[Slo Ogünemay 3.1] bucker.ini 수정한 이후 부팅 불가

### ISSUE THREAD

**Issue by Temaca333** [junhg0211/SloOS#13]
**버그 설명**
SloOS 3.1 버전에서 **'bucker.ini' 를 워드패드/메모장** 으로 열어 수정을 한 이후에 부팅시 아래와 같은 오류 발생
![image](https://user-images.githubusercontent.com/44523100/47616570-27443880-db02-11e8-9936-bbb4c0c7eba0.png)

**버그 발생 조건**
SloOS 3.1 버전에서 '**bucker.ini' 를 워드패드/메모장** 으로 열어 수정을 한 이후에 부팅이 안됨
ex:  윈도우, 배경화면, 독 색상 변경을 하고 그대로 저장을 해도 계속해서 같은 오류가 뜸

**Comment by junhg0211** [comment]
Slo Ogünemay 3.1.1 업데이트로 일단 수정은 했는데, `./slo/slo.ini`파일에 보면 `caption = 'Slo Ogünemay'` 부분이 있는데, 여기 있는 움라우트 u (ü)라는 문자가 `utf-8`이랑 `cp949`라는 인코딩 방식에서 처리가 안 되는 문자인 것 같아요. 그래서 발생하는 문제라서 `./slo/slo.ini`안에 있는 ü를 u로 바꾸고 프로그램에서는 Slo Ogunemay라고 출력을 하되, 인터넷같은 장소에서 - 움라우트 u를 잘 사용할 수 있는 곳에서는 Slo Ogünemay라는 명칭을 사용하는 걸로 결정했습니다.
지금 확인해보시면 아마 잘 될 거예요

**Comment by junhg0211** [comment]
확인 한 다음에 코멘트 남겨주세용
