### ISSUE TITLE
Dock 기능

### ISSUE THREAD

**Issue by Temaca333** [junhg0211/SloOS#16]
마우스를 화면 하단에 위치하면 독이 나오지만 그 이후 들어가는 기능이 없음

-> 나중에 설정에다 아래 두 가지 방법으로 설정 가능하게 했으면 함

[ ] - 독 자동 숨기기 (마우스를 하단으로 내렸을때만 독이 나오고 하단에서 마우스가 벗어나면 독이 자동으로 들어감)
[ ] - 독 유지 (처음부터 독이 아예 나와있으며 타 프로그램을 전체화면으로 했을 경우 독은 프로그램 뒤로 가려지게 됨 이때 마우스를 하단으로 내리면 뒤에 가려졌던 독이 나타나는 방식

**Comment by junhg0211** [comment]
#10 으로 병합
