### ISSUE TITLE
잠금화면에서도 창이 보이게됨

### ISSUE THREAD

**Issue by Temaca0506** [junhg0211/SloOS#2]
처음 부팅(?)하고 잠금화면을 풀고 창을 하나 새로 만든 다음 다시 잠금화면으로 이동하고
창이 가려진 부분을 클릭하면 레이어가 앞으로 오듯이 잠금화면에서도 창이 보이게 됨

![1](https://user-images.githubusercontent.com/44502513/47572238-790b8800-d975-11e8-8d2a-0fc8f3ce5ea0.PNG)
![2](https://user-images.githubusercontent.com/44502513/47572240-7ad54b80-d975-11e8-9d2d-256178db645f.PNG)
![default](https://user-images.githubusercontent.com/44502513/47572054-04d0e480-d975-11e8-92e8-abe2f6a82ad1.PNG)

**Comment by junhg0211** [comment]
`LockScreen` 오브젝트 생성 시에 `RootObject.highlight`를 `LockScreen`으로 설정함으로 다른 오브젝트의 입력을 제한, **오류 수정 완료되었습니다.** 테스트 부탁드립니다.
